version: "3.9"
services:
  jenkins-docker:
    image: docker:dind
    ports:
      - "2376:2376"
    networks:
      jenkins:
        aliases:
          - docker
    restart: "no"
    volumes:
      - "jenkins-docker-certs:/certs/client"
      - "jenkins-data:/var/jenkins_home"
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins-server:
    build:
      context: ./
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    restart: "no"
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:

